core/urls.py
from django.urls import path
from . import views

app_name = 'core'
urlpatterns = [
    path('', views.index, name='index'),
    path('new/', views.new, name='new'),
    path('list/', views.list_entries, name='list'),
    path('<int:id>', views.detail, name="detail"),
    path('<int:id>/edit', views.edit, name="edit"),
    path('<int:id>/delete', views.delete, name='delete'),
    path('<int:id>/sheet', views.view_sheet, name='sheet')
]

mileage_logger/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.contrib.auth import views as auth_views
from core.views import index as app_index
from django.urls import reverse_lazy
from django.views.generic import RedirectView
from users.views import PasswordResetConfirmViewCustom

urlpatterns = [
    path('', RedirectView.as_view(url=reverse_lazy('core:index'), permanent=False)),
    path('app/', include('core.urls')),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('login/', auth_views.LoginView.as_view(),name='login'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmViewCustom.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

users/urls.py
from django.urls import path
from .views import SignUpView, edit

app_name = 'users'
urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
    path('edit/', edit, name='edit')
]

core/models.py
from django.db import models
from datetime import datetime, timedelta
from django.utils import timezone
from django.conf import settings
from django.contrib.staticfiles import finders 
from decimal import Decimal
import math
from users.models import CustomUser

from openpyxl import load_workbook
from preferences.models import Preferences
from preferences import preferences

# Create your models here.

class CoreAppSettings(Preferences):
    class Meta:
        verbose_name_plural = "core app settings"
    reimbursement_rate = models.FloatField(default=0.53)
    abci_send_to_email = models.CharField(max_length=255, default='jacksonfoster444@gmail.com')
    myz_send_to_email = models.CharField(max_length=255, default='jacksonfoster444@gmail.com')
    acorn_send_to_email = models.CharField(max_length=255, default='jacksonfoster444@gmail.com')
    abci_contact_name = models.CharField(max_length=255, default='Mel')
    myz_contact_name = models.CharField(max_length=255, default='Brad')
    acorn_contact_name = models.CharField(max_length=255, default='Brad')
    cc_email = models.CharField(max_length=255, default='jackson@jacksonwfoster.com')

class Entry(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)

    entry_date = models.DateField('Date of entry')
    pub_date = models.DateField('Last modified')
    destination = models.CharField(max_length=500)
    notes = models.CharField(max_length=500, blank=True)
    odo_start = models.FloatField(default=0)
    odo_end = models.FloatField(default=0, null=True, blank=True)
    pay_period_start = models.DateField('Week start')
    pay_period_end = models.DateField('Week end')
    draft = models.BooleanField(default=True)
    emailed = models.BooleanField(default=False)

    
    start_of_pay_period = 4 # friday
    end_of_pay_period = 3 # thursday


    def __str__(self):
        return "{} - {} - {}".format(self.entry_date, self.destination, self.miles_driven())

    @staticmethod
    def current_entries(user, date=timezone.now().date()):
        current_entries = Entry.objects.filter(
            user=user, 
            pub_date__gte=Entry().get_start_of_pay_period_date(date=date), # current pay period
            pub_date__lte=Entry().get_end_of_pay_period_date(date=date) # current pay period
            )
        return current_entries



    def miles_driven(self):
        if self.odo_end:
            return math.ceil(self.odo_end - self.odo_start)
        else:
            return 0
    


    def amount_reimbursed(self, rate=None):
        if rate is None: # preferences gets screwy when running tests
            if preferences.CoreAppSettings.reimbursement_rate:
                rate = preferences.CoreAppSettings.reimbursement_rate
            else:
                rate = 0.53

        total = rate * self.miles_driven()
        return Decimal('{:.2f}'.format(round(total,2)))
    

    def get_start_of_pay_period_date(self, date=None):
        if date is None: 
            if self.pub_date: 
                date = self.pub_date
            else:
                date = timezone.now().date()

        one_week = timedelta(days=7)

        if date.weekday() >= self.start_of_pay_period: # friday, saturday and sunday
            return (date - timedelta(days=(date.weekday()-self.start_of_pay_period)))
        else:
            difference = self.start_of_pay_period - date.weekday()
            upcoming_friday = date + timedelta(days=difference)

            last_friday = upcoming_friday - one_week

            return last_friday


    def get_end_of_pay_period_date(self, date=None):
        if date is None: 
            if self.pub_date: 
                date = self.pub_date
            else:
                date = timezone.now().date()

        one_week = timedelta(days=7)

        if date.weekday() <= self.end_of_pay_period:
            difference = self.end_of_pay_period - date.weekday()
            upcoming_thursday = date + timedelta(days=difference)
            return upcoming_thursday
        else:
            difference = self.end_of_pay_period - date.weekday()
            last_thursday = date + timedelta(days=difference)

            next_thursday = last_thursday + one_week

            return next_thursday

core/forms.py
from django.forms import ModelForm
from .models import Entry
from preferences import preferences
from django.utils import timezone
from django import forms

class EntryForm(ModelForm):
    class Meta:
        model = Entry
        fields = ['entry_date', 'destination', 'notes', 'odo_start', 'odo_end']
        widgets = {
            'entry_date': forms.DateTimeInput(attrs={'placeholder': 'M/D/YYYY'}, format="%m/%d/%y"),
        }
    
    def save(self, request, commit=True):
        obj = super().save(commit=False)
        obj.user = request.user
        obj.pub_date = timezone.now().date()
        obj.pay_period_start = obj.get_start_of_pay_period_date()
        obj.pay_period_end = obj.get_end_of_pay_period_date()
        
        if 'save' in request.POST:
            obj.draft = False
        elif 'save_as_draft' in request.POST:
            obj.draft = True

        if commit:
            obj.save()
        else:
            return obj
        

core/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Entry
from .forms import EntryForm
from preferences import preferences
from core.utils import Spreadsheet
from datetime import timedelta
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from decimal import Decimal


@login_required
def index(request):
    messages = []
    entries = Entry.current_entries(request.user)

    drafts = list(filter(lambda x: x.draft == True, entries))
    current_drafts = list(zip(drafts, list(map(lambda x: EntryForm(instance=x), drafts))))
    
    current_entry_list = list(filter(lambda x: x.draft == False, entries))
    current_entries = list(zip(current_entry_list, list(map(lambda x: EntryForm(instance=x), current_entry_list))))
    
    miles_driven_this_period = sum(map(lambda x: x.miles_driven(), current_entry_list))
    reimbursement_this_period = Decimal('{:.2f}'.format(miles_driven_this_period * preferences.CoreAppSettings.reimbursement_rate, 2)) # pylint: disable=no-member
    all_entries = list(Entry.objects.filter(user=request.user, draft=False))
    return render(request, 'core/index.html', {'current_entries': current_entries,
                                                'current_drafts': current_drafts, 
                                                'miles_driven_this_period': miles_driven_this_period, 
                                                'reimbursement_this_period': reimbursement_this_period,
                                                'form': EntryForm(initial={'odo_start': None, 'odo_end': None}),
                                                'total_reimbursement': sum(map(lambda x: x.amount_reimbursed(), all_entries)),
                                                'total_miles_driven': sum(map(lambda x: x.miles_driven(), all_entries)),
                                                'start_of_this_pay_period': Entry().get_start_of_pay_period_date().strftime("%b %d %Y"),
                                                'end_of_this_pay_period': Entry().get_end_of_pay_period_date().strftime("%b %d %Y")
                                                })


@login_required
def list_entries(request):
    entries = list(Entry.objects.filter(user=request.user, draft=False))
    entries.reverse()
    dict = { }
    pay_periods = []
    for entry in entries:
        date = entry.pay_period_start
        if date in dict:
                dict[date].append(entry)
        else:
                dict[date] = [entry]
    for d in dict.keys():
        pay_periods.append({'start_date': d, 'end_date': d + timedelta(days=6), 'entries': dict[d]})
    for period in pay_periods:
        forms = []
        for entry in period['entries']:
            forms.append(EntryForm(instance=entry))
        period['entries'] = zip(period['entries'], forms)
    return render(request, 'core/list.html', {'pay_periods': pay_periods})
    


@login_required
def new(request):
    if request.method == 'POST':
        form = EntryForm(request.POST)
        if form.is_valid():
            form.save(request)
            return redirect('core:index')
        else:
            return render(request, 'core/new.html', {'form': form})
    else:
        form = EntryForm()
        return render(request, 'core/new.html', {'form': form})


@login_required
def detail(request, id):
    entry = Entry.objects.get(id=id)
    return render(request, 'core/detail.html', {'entry': entry})
 

@login_required
def edit(request, id):
    entry = Entry.objects.get(id=id)
    if not entry:
        redirect('core:app')
    warning = None
    if entry.pub_date < entry.get_start_of_pay_period_date(date=timezone.now().date()):
        warning = "This entry will be moved to the current pay period. Are you sure you want to continue?"

    if request.method == 'POST':
        form = EntryForm(request.POST, instance=entry)

        if form.is_valid():
            form.save(request)
            return redirect('core:index')
        else:
            return render(request, 'core/edit.html', {'form': form, 'entry': entry, 'warning': warning })

    else:
        form = EntryForm(instance=entry)
        return render(request, 'core/edit.html', {'form': form, 'entry': entry, 'warning': warning})


@login_required
def delete(request, id):
    Entry.objects.filter(id=id).delete()
    return redirect('core:index')


@login_required
def view_sheet(request, id):
    entry = Entry.objects.get(id=id)
    entries = Entry.current_entries(request.user, entry.pub_date)
    sheet = Spreadsheet(request.user, entries).as_dict()
    keys = []
    for key in sheet['entries'][0].keys():
            keys.append(key.title().replace("_", " "))
    return render(request, 'core/sheet.html', {'keys': keys,'sheet': sheet, 'pay_period_start': entry.pay_period_start, 'pay_period_end': entry.pay_period_end})
    

core/templates/core/base.html
    {% include 'core/header.html' %}
    <div class="pb-4 px-0">
        {% block content %}
        {% endblock %}
    </div>
    {% include 'core/footer.html' %}

core/templates/core/detail.html
{% extends 'core/base.html' %}

{% block content %}
<h5>Date Published: {{entry.pub_date }} </h5>
<hr>
<h5>Date: {{ entry.entry_date }}</h5>
<h1>Destination: {{ entry.destination }}</h1>
<h3>Notes: {{ entry.notes }}</h3>
<h2>Miles Driven: {{ entry.miles_driven }}</h2>
<h2>Amount Reimbursed: ${{ entry.amount_reimbursed }}</h2>


<a href="{% url 'core:edit' entry.id %}">Edit</a> | <a href="{% url 'core:delete' entry.id %}">Delete</a> | <a href="{% url 'core:sheet' entry.id %}">View Sheet</a><br><br>
<a href="{% url 'core:index'%}">Home</a>
{% endblock %}

core/templates/core/edit.html
{% extends 'core/base.html' %}

{% block content %}
{{ form.errors }}
{% if warning %}
    {{ warning }}
{% endif %}
<form action='{% url "core:edit" entry.id %}' method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-secondary"name="save_as_draft">Save as Draft</button>
    <button type="submit" class="btn btn-primary"name="save">Save</button>
</form>
{% endblock %}

core/templates/core/email.html
{% autoescape off %}
To initiate the password reset process for your mileage tracking account,
click the link below:

{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}

If clicking the link above doesn't work, please copy and paste the URL in a new browser
window instead.

Please email me at jackson@jacksonwfoster.com if you have any issues...

Jackson

{% endautoescape %}

core/templates/core/footer.html
</div>
</div>
<script src="{% static 'core/js/popper.min.js' %}"></script>
<script src="{% static 'core/js/bootstrap.min.js' %}"></script>
</main>

</body>
</html>

core/templates/core/header.html
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta charset="utf-8">
  <title>{% block title %}MileageTFW{% endblock %}</title>
  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'core/css/bootstrap.min.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'core/css/style.css' %}">
  <script src="{% static 'core/js/jquery.min.js' %}"></script>

</head>
<body>
  <main>
      {% if request.path != '/app/' %}
      <div class="container-fluid p-0">
            <nav class="navbar navbar-default navbar-fixed-top background navbar-expand-lg navbar-light bg-light">
                    <a class="navbar-brand-white" href="{% url 'core:index' %}">MileageTFW</a>
                    <button class="white-toggler navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                      <span class="white-toggler navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarNav">
                      <ul class="navbar-nav ml-auto">
                        <li class="nav-item active">
                          <a class="nav-link" href="{% url 'core:index' %}">Home <span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link" href="{% url 'core:index' %}?new=1">New Entry</a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link" href="{% url 'core:list' %}">All Entries</a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link" href="{% url 'users:edit' %}">Edit Profile</a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                        </li>
                      </ul>
                    </div>
                  </nav>
      </div>
       
        {% endif %}
        

core/templates/core/list.html
{% extends 'core/base.html' %}

{% block content %}
<div class="container">
    <div class="row py-4 px-3">
            {% if pay_periods %}
            <div class="col-md-12">
                <div class="list-group">
                    {% for pay_period in pay_periods %}
                    <p class="lead mt-3">{{ pay_period.start_date }} -- {{ pay_period.end_date }}</p>
                    {% for entry, form in pay_period.entries %}
                        <div id="entry_row_{{entry.id}}" data-toggle="modal" class="row list-entry" data-target="#entry_{{entry.id}}">
                                <div class='totals-number col-6'>
                                    {{ entry.destination }} <div class='badge miles-badge badge-red'>{{ entry.miles_driven }} miles</div>
                                    <br>
                                    <div class='totals-title'>{{ entry.entry_date }}</div>
                                </div>
                                <div class="entry-reimbursement col-6">
                                    <span class='entry-reimbursement-text'>${{ entry.amount_reimbursed }}</span>
                                </div>
                            </div>
                            <div class="modal fade" id="entry_{{ entry.id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                    <div class="modal-dialog" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                        <h5 class="modal-title" id="exampleModalLabel">Edit Entry</h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                        </div>
                                        <form id='form_{{entry.id}}'action='{% url "core:edit" id=entry.id %}' method="POST">  
                                            <div class="modal-body">
                                                {{ form.errors }}
                                                {% csrf_token %}
                                                {{ form.as_p }}
                                            </div>
                                            <script type="text/javascript">
                                                    $("#form_{{entry.id}} #id_entry_date").after('<button type="button" onclick=todaysDate() class="btn btn-danger ml-2 todays-date">Today</button>')
                                                    function postToDelete() {
                                                        $.ajax({
                                                                url: '{% url "core:delete" id=entry.id %}',
                                                                type: "POST",
                                                                data: {csrfmiddlewaretoken: '{{csrf_token}}' },
                                                                success: setTimeout(function(){window.location.reload();},100),
                                                        })
                                                        return false
                                                    };
                                                    function todaysDate(){
                                                        var today = new Date();
                                                        var dd = String(today.getDate()).padStart(2, '0');
                                                        var mm = String(today.getMonth() + 1).padStart(2, '0'); //January is 0!
                                                        var yyyy = today.getFullYear();
                                
                                                        today = mm + '/' + dd + '/' + yyyy;
                                                        
                                                        $("#form_{{entry.id}} #id_entry_date").val(today)
                        
                                                    }
                                                </script>
                                            <div class="modal-footer">
                                            <button onclick='postToDelete()' type='button' name="delete" class="btn btn-danger view-sheet">Delete</button>
                                            <button style="overflow: visible !important; height: 0 !important; width: 0 !important; margin: 0 !important; border: 0 !important; padding: 0 !important; display: block !important;" type="submit" name="save"></button>
                                            <a href="{% url 'core:sheet' id=entry.id %}" class="btn btn-success">View Sheet</a>
                                            <button type="submit"name="save_as_draft" class="btn btn-warning">Save as Draft</button>
                                            <button type="submit" name="save" class="btn btn-primary">Save</button>
                                            
                                        </form>
                                            </div>
                                    </div>
                                </div>
                            </div>
                    {% endfor %}
                {% endfor %}
                </div>
            {% else %}
                <p>No entries are available.</p>
            </div>
            {% endif %}
    </div>   
</div>
{% endblock %}

core/templates/core/new.html
{% extends 'core/base.html' %}
{% block content%}
{{ form.errors }}
<form action='{% url "core:new" %}' method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" name="save_as_draft">Save as Draft</button>
    <button type="submit" name="save">Save</button>

</form>
<a href="{% url 'core:index'%}">Home</a>
{% endblock %}

core/templates/core/sheet.html
{% extends 'core/base.html' %}

{% block content %}
<div style="overflow: scroll" class="container">
<h1 class="sheet-pay-period">{{ pay_period_start }} - {{ pay_period_end }}</h1>
<table style="overflow-x: scroll"class="table">
        <thead>
          <tr>
            <th scope="col">Entry Date</th>
            <th scope="col">Destination</th>
            <th scope="col">Notes</th>
            <th scope="col">Odometer Start</th>
            <th scope="col">Odometer End</th>
            <th scope="col">Mileage</th>
            <th scope="col">Reimbursement</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            {% for entry in sheet.entries %}
                <tr>
                {% for k,v in entry.items %}
                    <td>{{ v }}</td>
                {% endfor %}
                </tr>
            {% endfor %}
            <th scope="row">Total</th>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>{{sheet.total_mileage}} miles</td>
            <td>${{sheet.total_reimbursement}}</td>

          </tr>
        </tbody>
      </table>
    </div>

{% endblock %}